from dataclasses import dataclass
from typing import Dict, Tuple


@dataclass(frozen=True)
class FeatureDefinition:
    """
    Canonical description of a market feature used by Fusion V3.
    """

    name: str
    default: float = 0.0
    value_range: Tuple[float, float] = (0.0, 1.0)
    description: str = ""


FEATURE_SCHEMA: Dict[str, FeatureDefinition] = {
    "price_delta": FeatureDefinition(
        name="price_delta",
        default=0.0,
        value_range=(-1.0, 1.0),
        description="Relative deviation from estimated market price.",
    ),
    "risk_score": FeatureDefinition(
        name="risk_score",
        default=0.5,
        value_range=(0.0, 1.0),
        description="Fraud and listing reliability score.",
    ),
    "signal_score": FeatureDefinition(
        name="signal_score",
        default=0.5,
        value_range=(0.0, 1.0),
        description="Overall confidence generated by market intelligence.",
    ),
    "dedup_score": FeatureDefinition(
        name="dedup_score",
        default=0.0,
        value_range=(0.0, 1.0),
        description="Duplicate confidence score.",
    ),
    "area_score": FeatureDefinition(
        name="area_score",
        default=0.5,
        value_range=(0.0, 1.0),
        description="Overall district attractiveness.",
    ),
    "internet_score": FeatureDefinition(
        name="internet_score",
        default=0.5,
        value_range=(0.0, 1.0),
        description="Internet quality estimation.",
    ),
    "noise_score": FeatureDefinition(
        name="noise_score",
        default=0.5,
        value_range=(0.0, 1.0),
        description="Environmental noise estimation.",
    ),
    "expat_score": FeatureDefinition(
        name="expat_score",
        default=0.5,
        value_range=(0.0, 1.0),
        description="Expat friendliness score.",
    ),
    "beach_score": FeatureDefinition(
        name="beach_score",
        default=0.0,
        value_range=(0.0, 1.0),
        description="Beach accessibility score.",
    ),
}


FEATURE_ORDER = tuple(FEATURE_SCHEMA.keys())
