services:

  postgres:
    image: postgres:15
    container_name: lentra-db
    environment:
      POSTGRES_USER: lentra
      POSTGRES_PASSWORD: lentra
      POSTGRES_DB: lentra
    ports:
      - "5432:5432"
    volumes:
      - lentra_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: lentra-redis
    ports:
      - "6379:6379"

  api:
    build: ../api
    container_name: lentra-api
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: ../worker
    container_name: lentra-worker
    depends_on:
      - redis

volumes:
  lentra_pg:
