version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: lentra-redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: lentra-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lentra
    ports:
      - "5432:5432"

  api:
    build:
      context: ..
      dockerfile: infra/api.Dockerfile
    container_name: lentra-api
    depends_on:
      - redis
      - db
    ports:
      - "8000:8000"

  worker:
    build:
      context: ..
      dockerfile: infra/worker.Dockerfile
    container_name: lentra-worker
    depends_on:
      - redis
      - db

  worker-stream:
    build:
      context: ..
      dockerfile: infra/worker-stream.Dockerfile
    container_name: lentra-worker-stream
    depends_on:
      - redis

  worker-retry:
    build:
      context: ..
      dockerfile: infra/worker-retry.Dockerfile
    container_name: lentra-worker-retry
    depends_on:
      - redis

  bot:
    build:
      context: ..
      dockerfile: infra/bot.Dockerfile
    container_name: lentra-bot
    depends_on:
      - api
      - redis

  miniapp:
    image: nginx:alpine
    container_name: lentra-miniapp
    ports:
      - "8080:80"
