FROM python:3.11-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1 \
    PYTHONPATH=/app

RUN pip install --upgrade pip

RUN pip install \
    fastapi \
    uvicorn \
    redis \
    pydantic \
    httpx \
    requests \
    aiogram \
    python-dotenv
