services:
  flyrum_bot:
    build: .
    container_name: flyrum_bot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - flyrum_redis
    networks:
      - flyrum_net

  db:
    image: postgres:15
    container_name: db
    networks:
      - flyrum_net

  flyrum_redis:
    image: redis:7
    container_name: flyrum_redis
    networks:
      - flyrum_net

networks:
  flyrum_net:
    driver: bridge
