ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS attempts INTEGER NOT NULL DEFAULT 0;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS max_attempts INTEGER NOT NULL DEFAULT 5;

ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS run_after TIMESTAMP WITHOUT TIME ZONE DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_tasks_retry
ON tasks (status, run_after, created_at);
